version: '3.7'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  solr:
    image: solr:8.0.0
    ports:
      - 8983:8983
    volumes:
      - type: bind
        source: ./solr-config/solrconfig.xml
        target: /opt/solr-8.0.0/server/solr/configsets/_default/conf/solrconfig.xml
      - type: bind
        source: ./solr-config/schema.xml
        target: /opt/solr-8.0.0/server/solr/configsets/_default/conf/schema.xml
