version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      - RAILS_MASTER_CODE=6ad6c231b93f6357ca4f327253322eeb
      - DB_HOST=db
      - SOLR_HOST=solr
      - REDIS_URL=redis://redis:6379
    command: bundle exec rspec
    depends_on:
      - db
      - solr
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  solr:
    image: ericroos13/sunspot-solr
    ports:
      - 8983:8983
volumes:
  gem_bundle_path:
  git_gem_bundle_path:
