production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: 0.0.0.0
    port: 8983
    log_level: INFO
    path: /solr/app-development

test:
  solr:
    hostname: 0.0.0.0
    port: 8983
    log_level: WARNING
    path: /solr/test
    
