production:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST") { '0.0.0.0' } %>
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST") { '0.0.0.0' } %>
    port: 8983
    log_level: INFO
    path: /solr/app-development

test:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST") { '0.0.0.0' } %>
    port: 8983
    log_level: WARNING
    path: /solr/test
   
